<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Constants for math -->
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}"/>
      <xacro:insert_block name="origin"/>
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0" iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0" izz="${0.5 * mass * radius * radius}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="box_inertial" params="sx sy sz mass *origin">
    <inertial>
      <mass value="${mass}"/>
      <xacro:insert_block name="origin"/>
      <inertia ixx="${0.0833333 * mass * (sy*sy + sz*sz)}" ixy="0.0" ixz="0.0" iyy="${0.0833333 * mass * (sx*sx + sz*sz)}" iyz="0.0" izz="${0.0833333 * mass * (sx*sx + sy*sy)}"/>
    </inertial>
  </xacro:macro>

  <!-- WHEEL MACRO -->
  <xacro:macro name="wheel" params="wheel_prefix parent_link left_right radius width wheel_mass *joint_origin">
    <link name="${wheel_prefix}_wheel">
      
      <xacro:cylinder_inertial length="${width}" mass="${wheel_mass}" radius="${radius}">
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      </xacro:cylinder_inertial>

      <visual>
        <origin rpy="${left_right * PI/2}  0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://myrobot_description/meshes/tire.dae" scale="${radius} ${radius} ${width/2}"/>
        </geometry>
      </visual>

      <collision>
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${wheel_prefix}_wheel_joint" type="continuous">
      <parent link="${parent_link}"/>
      <child link="${wheel_prefix}_wheel"/>
      <xacro:insert_block name="joint_origin"/>
      <axis rpy="0 0 0" xyz="0 1 0"/>
    </joint>

    <transmission name="${wheel_prefix}_wheel_trans" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${wheel_prefix}_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${wheel_prefix}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  <!-- OTHER -->
  <xacro:macro name="make_box_no_inertial" params="sx sy sz *origin">
    <collision>
      <xacro:insert_block name="origin"/>
      <geometry>
        <box size="${sx} ${sy} ${sz}"/>
      </geometry>
    </collision>
    <visual>
      <xacro:insert_block name="origin"/>
      <geometry>
        <box size="${sx} ${sy} ${sz}"/>
      </geometry>
      <material name="sky"/>
    </visual>
  </xacro:macro>

  <xacro:macro name="make_box" params="sx sy sz mass xyz">
    <xacro:make_box_no_inertial sx="${sx}" sy="${sy}" sz="${sz}">
      <origin rpy="0 0 0" xyz="${xyz}"/>
    </xacro:make_box_no_inertial>

    <xacro:box_inertial sx="${sx}" sy="${sy}" sz="${sz}" mass="${mass}">
      <origin rpy="0 0 0" xyz="${xyz}"/>
    </xacro:box_inertial>
  </xacro:macro>

  <xacro:macro name="make_box_link" params="parent name sx sy sz mass xyz">
    <link name="${name}">
      <xacro:make_box sx="${sx}" sy="${sy}" sz="${sz}" mass="${mass}" xyz="0 0 0"/>
    </link>

    <joint name="${name}_box_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <origin rpy="0 0 0" xyz="${xyz}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="ir_sensor" params="name parent sx sy sz *origin">
    <link name="ir_sensor_${name}">
      <visual>
        <origin rpy="0 0 0" xyz="${sx/2} 0 0"/>
        <geometry>
          <box size="${sx} ${sy} ${sz}"/>
        </geometry>
        <material name="green"/>
      </visual>
    </link>
    <joint name="ir_sensor_${name}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="ir_sensor_${name}"/>
      <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="ir_sensor_rot" params="name parent distance yaw pitch">
    <xacro:ir_sensor name="${name}" parent="${parent}" 
      sx="0.003" sy="0.008" sz="0.008">
      <origin rpy="0 ${pitch} ${yaw}"
       xyz="${distance*cos(yaw)} ${distance*sin(yaw)} 0"/>
    </xacro:ir_sensor>
  </xacro:macro>
</robot>
